# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

GROUP=io.github.olubunmialegbeleye.dragtoreveal
VERSION_NAME=0.1.0
POM_ARTIFACT_ID=dragtoreveal
POM_NAME=DragToReveal
POM_DESCRIPTION=A three-anchor swipe-to-reveal component for Jetpack Compose
POM_URL=https://github.com/olubunmialegbeleye/DragToReveal
POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0
POM_DEVELOPER_ID=olubunmialegbeleye
POM_DEVELOPER_NAME=Olubunmi Alegbeleye
POM_SCM_URL=https://github.com/olubunmialegbeleye/DragToReveal